# Generated by Django 5.0.3 on 2024-03-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='name',
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='story',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
