# Generated by Django 5.0.3 on 2024-03-26 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_story_author_story_date_story_details_story_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myApp.author'),
        ),
        migrations.AlterField(
            model_name='story',
            name='date',
            field=models.DateField(),
        ),
    ]
