# Generated by Django 5.0.3 on 2024-03-26 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_name_author_author'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Authors',
        ),
        migrations.RenameModel(
            old_name='Story',
            new_name='Stories',
        ),
    ]
